version: 2
jobs:
  build:
    working_directory: ~/Lusitaniae/dummy_exporter
    parallelism: 1
    shell: /bin/bash --login

    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      DOCKER_IMAGE_NAME: lusotycoon/dummy-exporter
      QUAY_IMAGE_NAME: quay.io/lusitaniae/dummy-exporter
      DOCKER_TEST_IMAGE_NAME: quay.io/prometheus/golang-builder:1.8-base
      REPO_PATH: github.com/Lusitaniae/dummy_exporter

    machine:
      image: circleci/classic:201708-01

    steps:
    - checkout

    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS

    - run:
        working_directory: ~/Lusitaniae/dummy_exporter
        command: sudo curl -L -o /usr/bin/docker 'https://s3-external-1.amazonaws.com/circle-downloads/docker-1.9.1-circleci'

    - run:
        working_directory: ~/Lusitaniae/dummy_exporter
        command: sudo chmod 0755 /usr/bin/docker

    - run:
        working_directory: ~/Lusitaniae/dummy_exporter
        command: sudo curl -L 'https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2' | tar xvjf - --strip-components 3 -C $HOME/bin

    - run:
        working_directory: ~/Lusitaniae/dummy_exporter
        command: echo -e "export DOCKER_IMAGE_NAME=lusotycoon/dummy-exporter\nexport QUAY_IMAGE_NAME=quay.io/lusitaniae/dummy-exporter\nexport DOCKER_TEST_IMAGE_NAME=quay.io/prometheus/golang-builder:1.8-base\nexport REPO_PATH=github.com/Lusitaniae/dummy_exporter" >> $BASH_ENV

    - run:
        working_directory: ~/Lusitaniae/dummy_exporter
        command: 'sudo docker info >/dev/null 2>&1 || sudo service docker start; '

    # This is based on your 1.0 configuration file or project settings
    - run: make promu
    - run: docker info
    # This is based on your 1.0 configuration file or project settings
    - run: promu crossbuild
    - run: ln -s .build/linux-amd64/dummy_exporter dummy_exporter
    - run: |
        if [ -n "$CIRCLE_TAG" ]; then
          make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$CIRCLE_TAG
          make docker DOCKER_IMAGE_NAME=$QUAY_IMAGE_NAME DOCKER_IMAGE_TAG=$CIRCLE_TAG
        else
          make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME
          make docker DOCKER_IMAGE_NAME=$QUAY_IMAGE_NAME
        fi
    # This is based on your 1.0 configuration file or project settings
    - run: mkdir $CIRCLE_ARTIFACTS/binaries/ && cp -a .build/* $CIRCLE_ARTIFACTS/binaries/
    - run: docker images


  deployment:
    filters:
      tags:
        only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
      branches:
        ignore: /.*/
    steps:
      - run: promu crossbuild tarballs
      - run: promu checksum .tarballs
      - run: promu release .tarballs
      - run: mkdir $CIRCLE_ARTIFACTS/releases/ && cp -a .tarballs/* $CIRCLE_ARTIFACTS/releases/
      - run: docker login -e $DOCKER_EMAIL -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
      - run: docker login -e $QUAY_EMAIL -u $QUAY_LOGIN -p $QUAY_PASSWORD quay.io
      - run:|
        if [[ "$CIRCLE_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$CIRCLE_TAG" "$DOCKER_IMAGE_NAME:latest"
            docker tag "$QUAY_IMAGE_NAME:$CIRCLE_TAG" "$QUAY_IMAGE_NAME:latest"
        fi
      - run: docker push $DOCKER_IMAGE_NAME
      - run: docker push $QUAY_IMAGE_NAME
